name: Build LaTeX

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        working-directory: ./${{ env.BRANCH }}
        shell: bash
        run: echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV\

      - name: Build PDF
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ${{ env.BRANCH }}
          root_file: main.tex

      - name: Set datetime release
        run: |
          export CUR_DATE=$(date +%Y-%m-%d-%T)
          echo "CUR_DATE=$CUR_DATE" >> $GITHUB_ENV
          echo "CUR_DATE_TAG=$(echo $CUR_DATE | tr : -)" >> $GITHUB_ENV

      - name: Rename main.pdf
        working-directory: ./${{ env.BRANCH }}
        run: mv "main.pdf" "$BRANCH-$CUR_DATE_TAG.pdf"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BRANCH }}-${{ env.CUR_DATE_TAG }}
          path: ${{ env.BRANCH }}/${{ env.BRANCH }}-${{ env.CUR_DATE_TAG }}.pdf
