name: Build and deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV

      - name: Split branch name
        id: split
        uses: rishabhgupta/split-by@v1
        with:
          string: ${{ env.BRANCH }}
          split-by: "/"

      - name: Extract fragments from branch name
        run: |
          echo "SEMESTER=${{ steps.split.outputs._1 }}" >> $GITHUB_ENV
          echo "SUBJECT=${{ steps.split.outputs._2 }}" >> $GITHUB_ENV

      - name: Build PDF
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./${{ env.SEMESTER }}/${{ env.SUBJECT }}
          root_file: main.tex

      - name: Upload pages artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.SEMESTER }}_${{ env.SUBJECT }}.pdf
          path: ./${{ env.SEMESTER }}/${{ env.SUBJECT }}/main.pdf
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV

      - name: Split branch name
        id: split
        uses: rishabhgupta/split-by@v1
        with:
          string: ${{ env.BRANCH }}
          split-by: "/"

      - name: Extract fragments from branch name
        run: |
          echo "SEMESTER=${{ steps.split.outputs._1 }}" >> $GITHUB_ENV
          echo "SUBJECT=${{ steps.split.outputs._2 }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - uses: actions/download-artifact@master
        with:
          name: ${{ env.SEMESTER }}_${{ env.SUBJECT }}.pdf
          path: .

      - name: Move PDF
        run: |
          mkdir -p ${{ env.SEMESTER }}
          mv main.pdf ${{ env.SEMESTER }}/${{ env.SUBJECT }}.pdf

      - name: Commit and push changes
        run: |
          git config --global user.name isagila
          git config --global user.email "isagila@mail.ru"
          git add "${{ env.SEMESTER }}/${{ env.SUBJECT }}.pdf"
          git commit -m "Update ${{ env.SEMESTER }}/${{ env.SUBJECT }}.pdf"
          git push
